name: Deploy to Expo and TestFlight

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Deploy to Expo with EAS Update
      run: npx eas update --branch main --message "Auto-update from GitHub Actions" --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        CI: 1
        
    - name: Build iOS app for TestFlight
      run: npx eas build --platform ios --profile production --non-interactive --no-wait
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        CI: 1

    - name: Submit iOS build to TestFlight
      run: npx eas submit --platform ios --profile production --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        CI: 1
